### ISSUE TITLE
Graphqlize java spring boot demo fails to start using my onw data

### ISSUE THREAD

**Issue by ieugen** [graphqlize/graphqlize#53]
Hello,

I've started the spring boot demo with my own data and it fails to start. 

I've used this setup https://github.com/graphqlize/graphqlize-demo/pull/5 . 
Using a database dump from my postgresql staging env I wanted to explore the API. 

I got this error:
```
graphqlize_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLizeResolverProvider' defined in URL [jar:file:/app/lib/spring-boot-0.0.1-SNAPSHOT.jar!/org/graphqlize/java/springboot/GraphQLizeResolverProvider.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.graphqlize.java.springboot.GraphQLizeResolverProvider]: Constructor threw exception; nested exception is java.lang.NullPointerException
graphqlize_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
graphqlize_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
graphqlize_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
graphqlize_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
graphqlize_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
graphqlize_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
graphqlize_1  | 	at org.graphqlize.java.springboot.Application.main(Application.java:10) [spring-boot-0.0.1-SNAPSHOT.jar:na]
graphqlize_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.graphqlize.java.springboot.GraphQLizeResolverProvider]: Constructor threw exception; nested exception is java.lang.NullPointerException
graphqlize_1  | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	... 19 common frames omitted
graphqlize_1  | Caused by: java.lang.NullPointerException: null
graphqlize_1  | 	at clojure.core$name.invokeStatic(core.clj:1595) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$name.invoke(core.clj:1589) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at graphqlize.lacinia.arg$order_by_arg.invokeStatic(arg.clj:27) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.arg$order_by_arg.invoke(arg.clj:24) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.arg$query_args.invokeStatic(arg.clj:38) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.arg$query_args.invoke(arg.clj:33) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.query$entity_meta_data__GT_collection_query.invokeStatic(query.clj:25) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.query$entity_meta_data__GT_collection_query.invoke(query.clj:22) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.query$generate$fn__5534.invoke(query.clj:32) ~[na:na]
graphqlize_1  | 	at clojure.core$map$fn__5866.invoke(core.clj:2755) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.lang.Cons.next(Cons.java:39) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.lang.RT.next(RT.java:713) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$next__5386.invokeStatic(core.clj:64) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$reduce1.invokeStatic(core.clj:944) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$reduce1.invokeStatic(core.clj:934) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$merge.invokeStatic(core.clj:3048) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$merge.doInvoke(core.clj:3041) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at clojure.core$apply.invoke(core.clj:660) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at graphqlize.lacinia.query$generate.invokeStatic(query.clj:29) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.query$generate.invoke(query.clj:28) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.core$schema.invokeStatic(core.clj:42) ~[na:na]
graphqlize_1  | 	at graphqlize.lacinia.core$schema.invoke(core.clj:38) ~[na:na]
graphqlize_1  | 	at graphqlize.java_interop$initialize.invokeStatic(java_interop.clj:10) ~[na:na]
graphqlize_1  | 	at graphqlize.java_interop$initialize.invoke(java_interop.clj:9) ~[na:na]
graphqlize_1  | 	at clojure.lang.Var.invoke(Var.java:384) ~[clojure-1.10.1.jar:na]
graphqlize_1  | 	at org.graphqlize.java.GraphQLizeResolver.<init>(GraphQLizeResolver.java:17) ~[graphqlize-java-0.1.0-alpha8.jar:na]
graphqlize_1  | 	at org.graphqlize.java.springboot.GraphQLizeResolverProvider.<init>(GraphQLizeResolverProvider.java:16) ~[spring-boot-0.0.1-SNAPSHOT.jar:na]
graphqlize_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_242]
graphqlize_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_242]
graphqlize_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_242]
graphqlize_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_242]
graphqlize_1  | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
graphqlize_1  | 	... 21 common frames omitted
```

**Comment by demystifyfp** [comment]
Hi @ieugen,

Can you share me the pg_dump or at least the schema alone to reproduce the issue?

For the stack trace, I couldn't find much.

**Comment by ieugen** [comment]
Sure. I'll see what I can do. I'll ping you in private.

**Comment by tamizhvendan** [comment]
The materialized view was not supported in GraphQLize earlier and it is now part of the latest release. Hence, I am closing this issue.
