### ISSUE TITLE
H2 PostgreSQL Compatibility Mode

### ISSUE THREAD

**Issue by odwrotnie** [graphqlize/graphqlize#58]
When using H2 in PostgreSQL Compatibility Mode - `jdbc:h2:~/test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE` you get:

```
Exception in thread "main" java.lang.IllegalArgumentException: No method in multimethod 'get-db-config' for dispatch value: H2
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at honeyeql.meta_data$fetch.invokeStatic(meta_data.clj:350)
	at honeyeql.meta_data$fetch.invoke(meta_data.clj:346)
	at honeyeql.db$initialize.invokeStatic(db.clj:12)
	at honeyeql.db$initialize.invoke(db.clj:7)
	at graphqlize.lacinia.core$schema.invokeStatic(core.clj:39)
	at graphqlize.lacinia.core$schema.invoke(core.clj:38)
	at graphqlize.java_interop$initialize.invokeStatic(java_interop.clj:10)
	at graphqlize.java_interop$initialize.invoke(java_interop.clj:9)
	at clojure.lang.Var.invoke(Var.java:384)
	at org.graphqlize.java.GraphQLizeResolver.<init>(GraphQLizeResolver.java:17)
	at app.instap.graphql.GraphQL.<init>(GraphQL.scala:29)
	at app.instap.graphql.Server$.delayedEndpoint$app$instap$graphql$Server$1(Server.scala:33)
	at app.instap.graphql.Server$delayedInit$body.apply(Server.scala:28)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at app.instap.graphql.Server$.main(Server.scala:28)
	at app.instap.graphql.Server.main(Server.scala)
```

**Comment by tamizhvendan** [comment]
Hi @odwrotnie, 

GraphQLize currently supports only Postgres (9.4 & above) and MySQL (8.0 & above).

**Comment by odwrotnie** [comment]
I could help with development of this feature. Let me know if it's something you want or not.

**Comment by tamizhvendan** [comment]
I am open to accepting the pull request. You can start by referring, how I have implemented the two databases. 

https://github.com/graphqlize/honeyeql/tree/master/src/honeyeql/db_adapter
